// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/** Avoid `localStorage` during SSR / RSC prerender (Next.js evaluates client modules on the server). */
function getAuthStorage(): Storage {
  if (typeof window !== "undefined") return localStorage;
  const mem: Record<string, string> = {};
  return {
    getItem: (key) => mem[key] ?? null,
    setItem: (key, value) => {
      mem[key] = value;
    },
    removeItem: (key) => {
      delete mem[key];
    },
    clear: () => {
      for (const k of Object.keys(mem)) delete mem[k];
    },
    get length() {
      return Object.keys(mem).length;
    },
    key: (i) => Object.keys(mem)[i] ?? null,
  } as Storage;
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});