// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

declare global {
  interface Window {
    __STAY_SUPABASE__?: { url?: string; anonKey?: string };
  }
}

function getEffectiveUrl(): string {
  if (typeof window !== "undefined" && window.__STAY_SUPABASE__?.url) {
    return window.__STAY_SUPABASE__.url;
  }
  return process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
}

function getEffectiveKey(): string {
  if (typeof window !== "undefined" && window.__STAY_SUPABASE__?.anonKey) {
    return window.__STAY_SUPABASE__.anonKey;
  }
  return process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "";
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/** Avoid `localStorage` during SSR / RSC prerender (Next.js evaluates client modules on the server). */
function getAuthStorage(): Storage {
  if (typeof window !== "undefined") return localStorage;
  const mem: Record<string, string> = {};
  return {
    getItem: (key) => mem[key] ?? null,
    setItem: (key, value) => {
      mem[key] = value;
    },
    removeItem: (key) => {
      delete mem[key];
    },
    clear: () => {
      for (const k of Object.keys(mem)) delete mem[k];
    },
    get length() {
      return Object.keys(mem).length;
    },
    key: (i) => Object.keys(mem)[i] ?? null,
  } as Storage;
}

let _client: SupabaseClient<Database> | null = null;

function getClient(): SupabaseClient<Database> {
  if (_client) return _client;
  const url = getEffectiveUrl();
  const key = getEffectiveKey();
  if (typeof window !== "undefined" && (!url || !key)) {
    console.error(
      "[Supabase] Missing URL or anon key. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY in NEXT JS/.env.local, restart npm run dev, and ensure SupabaseEnvScript runs in layout."
    );
  }
  _client = createClient<Database>(url, key, {
    auth: {
      storage: getAuthStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  return _client;
}

/** Lazy singleton; reads window.__STAY_SUPABASE__ on the client when set by SupabaseEnvScript. */
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop, receiver) {
    const c = getClient();
    const v = Reflect.get(c, prop, receiver);
    if (typeof v === "function") {
      return (v as (...args: unknown[]) => unknown).bind(c);
    }
    return v;
  },
});
